add tsukuba2023 maps by m1
KBKN-Autonomous-Robotics-Lab/kbkn_maps pull request #25
Opened 2023-11-07 14:59 UTC by shunsugar

## PR Type

- [x] Feature
- [ ] Bug fix
- [ ] Refactor
- [ ] Documentation
- [ ] Other

## Overview
- つくばチャレンジ2023におけるOrange2023 Middleの各マップとウェイポイントを追加しました。

## Detail
- tsukuba2023_originalは実際にとれた生のマップです。
- tsukuba2023_editedはoriginalのノイズを一部修正したマップです。

2023-11-08 07:18 UTC, shunki1006 commented
ノイズを一部修正したmapというのは, 編集アプリを用いてpgm上の黒点を消したということでしょうか？
もしそうであればoriginalは使う予定がなく必要ない気がするのですがいかがでしょうか？

2023-11-08 08:20 UTC, shunsugar commented
その通りです。originalはowncloudに挙げておきます。

2023-11-08 08:27 UTC, shunki1006 requested changes
maps, waypoint共に名前が統一されていないのが気になります. 
confirmation_run_Middleのように名前をつけるよう決まりなので, 各ファイルの名前を一眼見てどこまでのものなのかわかるようにしていただけますと幸いです. 
m2のmapsなどをご参照ください.

2023-11-08 08:27 UTC, shunki1006 commented
> その通りです。originalはowncloudに挙げておきます。

ご対応ありがとうございます.

2023-11-08 08:30 UTC, shunki1006 commented
もう一点なのですが, ROS2では以下のようにディレクトリを指定してその中にmap_merger後の全てのmaps, waypointsを入れているのですが, multi_mapの切り替えはROS1ではディレクトリ指定ではなく, ファイル指定なのでしょうか？

  <arg name="multi_map_dir" default="$(find-pkg-share kbkn_maps)/multi_map/hosei/m2/courtyard"/>
  <arg name="start_map_num" default="0"/>
  <arg name="map_file_path" default="$(var multi_map_dir)/map$(var start_map_num).yaml"/>
  <arg name="waypoints_file" default="$(var multi_map_dir)/waypoints.yaml"/>

2023-11-08 11:33 UTC, Alpaca-zip requested changes, later dismissed
<img src="https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/assets/84959376/d34f40b3-b5e6-4254-98e1-4b45dff669dd" width="400px">

上記のようにファイルの末尾に禁止マークがついているのは、最後に改行が挿入されていないことを意味しているので、一行改行を入れるようにしてください。

なぜ改行を入れなければいけないかというと、POSIXという規格でそう決まっているからです。いくつかのプログラミング言語では、改行で終わらないコードは正しく動くことが保証されていないので注意しましょう。

2023-11-08 13:12 UTC, shunsugar commented
> もう一点なのですが, ROS2では以下のようにディレクトリを指定してその中にmap_merger後の全てのmaps, waypointsを入れているのですが, multi_mapの切り替えはROS1ではディレクトリ指定ではなく, ファイル指定なのでしょうか？
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/blob/39709d2dfaeef24aeccaf0e0efc008d0f6444f6c/orange_navigation/launch/multi_map_navigation.launch.xml#L5

ROS2と同様に, ROS1でもmulti_mapのmapの切り替えはディレクトリ指定ですが, waypointsに関してはファイル指定になっています. そのディレクトリにmap_merger後の全てのmaps, waypointsを入れています. ROS1では, 以下の部分が対応していると思います.
[https://github.com/KBKN-Autonomous-Robotics-Lab/tsukuba2023-src/blob/62f1c4280878de23ccb1f8cc6d3eea51a5964d39/tsukuba2023/launch/teb_waypoint_navigation_multi.launch#L4](url)

2023-11-08 13:18 UTC, shunsugar commented
> 上記のようにファイルの末尾に禁止マークがついているのは、最後に改行が挿入されていないことを意味しているので、一行改行を入れるようにしてください。
なぜ改行を入れなければいけないかというと、POSIXという規格でそう決まっているからです。いくつかのプログラミング言語では、改行で終わらないコードは正しく動くことが保証されていないので注意しましょう。

なるほど、知らなかったです。ありがとうございます。

ちなみに、ウェイポイントファイルのような、自分でコードを書くわけではなく、自動的に保存されるようなファイルでもそのような注意を払うべきですか？

2023-11-08 13:39 UTC, shunki1006 commented
> > もう一点なのですが, ROS2では以下のようにディレクトリを指定してその中にmap_merger後の全てのmaps, waypointsを入れているのですが, multi_mapの切り替えはROS1ではディレクトリ指定ではなく, ファイル指定なのでしょうか？
> > https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/blob/39709d2dfaeef24aeccaf0e0efc008d0f6444f6c/orange_navigation/launch/multi_map_navigation.launch.xml#L5
> 
> ROS2と同様に, ROS1でもmulti_mapのmapの切り替えはディレクトリ指定ですが, waypointsに関してはファイル指定になっています. そのディレクトリにmap_merger後の全てのmaps, waypointsを入れています. ROS1では, 以下の部分が対応していると思います. [https://github.com/KBKN-Autonomous-Robotics-Lab/tsukuba2023-src/blob/62f1c4280878de23ccb1f8cc6d3eea51a5964d39/tsukuba2023/launch/teb_waypoint_navigation_multi.launch#L4](url)

そうみたいですね, ただ, 全学年のものでファイルの保存方法を統一したいので, /multi_map/tsukuba/m1直下に1つフォルダを置いてカラ保存するように変更してください. 

これは本PRの内容には直結しないのですが, launchでの指定の仕方をROS2仕様に変えた方がmulti_mapの切り替えの際に便利かと思うのでよかったら検討してみてください.

2023-11-08 13:41 UTC, shunki1006 commented
@shunsugar 各ファイルの名前の変更, /multi_map/tsukuba/m1直下へのフォルダの追加, waypointsファイル最後への改行の追加の3点をご対応お願いいたします.

2023-11-08 14:12 UTC, Alpaca-zip commented
> ちなみに、ウェイポイントファイルのような、自分でコードを書くわけではなく、自動的に保存されるようなファイルでもそのような注意を払うべきですか？

以下で、テキストファイルの末尾は改行で終わると記述されているので、コードに限らず改行を入れておくのが無難だと思います。
https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap03.html#:~:text=3.392%20Text%20File,INPUT%20FILES%20sections.

2023-11-08 14:15 UTC, shunsugar commented
> 以下で、テキストファイルの末尾は改行で終わると記述されているので、コードに限らず改行を入れておくのが無難だと思います。
https://pubs.opengroup.org/onlinepubs/000095399/basedefs/xbd_chap03.html#:~:text=3.392%20Text%20File,INPUT%20FILES%20sections.

わかりました。わざわざありがとうございます。

2023-11-08 14:18 UTC, shunsugar commented
@shunki1006 3点の対応をいたしました. ご確認のほどよろしくお願いいたします.

2023-11-08 14:21 UTC, shunki1006 requested changes
無闇に全部に改行するのではなく, git上でみて赤いマークがついている部分のみ変更した方が適していると思います.

2023-11-08 14:21 UTC, shunki1006 commented on waypoints/tsukuba/m1/inside_the_park_Middle.yaml
> +
改行が一つ多いです.

2023-11-08 14:21 UTC, shunki1006 commented on waypoints/tsukuba/m1/goal_Middle.yaml
> +
ここもです.

2023-11-08 14:21 UTC, shunki1006 commented on waypoints/tsukuba/m1/confirmation_run_Middle.yaml
> +
ここもです.

2023-11-08 14:21 UTC, shunki1006 commented on maps/tsukuba/m1/traffic_light_Middle.yaml
> +
ここもです.

2023-11-08 14:21 UTC, shunki1006 commented on maps/tsukuba/m1/inside_the_park_Middle.yaml
> +
ここもです.

2023-11-08 14:21 UTC, shunki1006 commented on maps/tsukuba/m1/goal_Middle.yaml
> +
ここもです.

2023-11-08 14:21 UTC, shunki1006 commented on maps/tsukuba/m1/confirmation_run_Middle.yaml
> +
ここもです.

2023-11-08 14:23 UTC, shunki1006 commented
> @shunki1006 3点の対応をいたしました. ご確認のほどよろしくお願いいたします.

今指摘した点以外は修正されていたので, あと1つだけご対応お願いいたします.

2023-11-08 14:56 UTC, shunsugar commented
ちなみになんですけど、b3やm2のファイルでは改行がされていないのですが、禁止マークは出ないのですか？

2023-11-08 14:57 UTC, shunsugar commented
@shunki1006 今度こそ対応できたと思います.

2023-11-08 15:05 UTC, shunki1006 commented
> @shunki1006 今度こそ対応できたと思います.



> @shunki1006 今度こそ対応できたと思います.

改行が多いと指摘した部分が修正されていないと思います. 
現状だと以下のようになってしまう(不必要な62行目ができてしまう)ので改行を減らして, カーソルを先頭にもっていった状態で保存してください. 
自分の経験上, 最後のカーソルの位置が先頭にない場合でもエラーマークが出てしまうので注意してください. 
![スクリーンショット 2023-11-09 0 01 18](https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/assets/88425011/1d8ec609-e8ea-4e98-a3c9-028565ffb869)

2023-11-08 15:09 UTC, shunki1006 commented
> ちなみになんですけど、b3やm2のファイルでは改行がされていないのですが、禁止マークは出ないのですか？

上ではなく下の状態で保存するとエラーマークは出ないです. 
エラーマークが出ていなければフォーマッターが調整してくれるのでmainにあがる際には最終行に不必要な改行はなくなります. 
![スクリーンショット 2023-11-09 0 06 18](https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/assets/88425011/7ebcc524-bea1-4b58-9345-3106f1cf81c3)
![スクリーンショット 2023-11-09 0 06 27](https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/assets/88425011/c3b016d0-1333-4275-a460-855d7bb8379a)

2023-11-09 01:26 UTC, shunsugar commented
> 上ではなく下の状態で保存するとエラーマークは出ないです.
エラーマークが出ていなければフォーマッターが調整してくれるのでmainにあがる際には最終行に不必要な改行はなくなります.

こちらの方では下の状態のように改行を一回しているのですが, そちらで見ると上の状態になっているということですか？

2023-11-09 04:39 UTC, shunki1006 commented
> > 上ではなく下の状態で保存するとエラーマークは出ないです.
> > エラーマークが出ていなければフォーマッターが調整してくれるのでmainにあがる際には最終行に不必要な改行はなくなります.
> 
> こちらの方では下の状態のように改行を一回だけしているのですが, そちらで見ると上の状態になっているということですか？

はい, 本PRのFiles Changedを見るとそのようになっておりました. 
ただ今回のcommitで改善されていますのでもう問題ないです. 
多くの修正依頼にご対応いただきありがとうございます.

2023-11-09 04:40 UTC, shunki1006 approved these changes

2023-11-09 04:41 UTC, merged