add_waypoints_file
KBKN-Autonomous-Robotics-Lab/kbkn_maps pull request #4
Opened 2023-10-16 06:45 UTC by shunki1006

## PR Type

- [x] Feature
- [ ] Bug fix
- [ ] Refactor
- [ ] Documentation
- [ ] Other

## Overview
- waypointsファイルの管理場所の変更. 

## Detail
- waypointsファイルの管理場所をmapsの中に作るのではなく, mapsと並列した場所に変更しました. ex)kbkn_maps/maps/hosei/waypoints/20231011_Senior.yamlで管理していたものを, kbkn_maps/waypoints/hosei/20231011_Senior.yamlで管理する

2023-10-16 06:54 UTC, shunki1006 commented
@Alpaca-zip  cartographerとslam_toolboxのウェイポイントナビゲーションではorange_ros2/orange_navigation/config/waypoints.yamlを使用していることは確認できたのですが, 今回の変更で移動させたkbkn_maps内のwaypointsをどこで使用しているのかが見つかりませんでした.
もし, 使用しているのであればご指摘お願いいたします. 
また, kbkn_maps内のファイルを指定するように変更したい際にはorange_navigation内で出しているPRの方にもコメントいただけますと幸いです.

2023-10-16 15:42 UTC, Alpaca-zip requested changes
9/23の実験走行時にB3は機体を出していないのでこのフォルダは削除してもらえますか？
https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/tree/feature/waypoints_file/maps/tsukuba/20230923/b3
___
> @Alpaca-zip cartographerとslam_toolboxのウェイポイントナビゲーションではorange_ros2/orange_navigation/config/waypoints.yamlを使用していることは確認できたのですが, 今回の変更で移動させたkbkn_maps内のwaypointsをどこで使用しているのかが見つかりませんでした.
もし, 使用しているのであればご指摘お願いいたします.
また, kbkn_maps内のファイルを指定するように変更したい際にはorange_navigation内で出しているPRの方にもコメントいただけますと幸いです.

以下です。
https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/blob/7aecec11b5da80e2ab86b0e8ca499bc506ad13dd/orange_navigation/src/waypoint_follower_client.cpp#L9

ただし、waypoint_follower_clientを含め、既存のorange_ros2/orange_navigationの内容は全面的に廃止(@koki0624 が作成してくれた[orange_navigaion](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation)に置き換え)をする予定なので、そちらの対応は[orange_navigaion](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation)の作業が落ち着いた後でよいと思います。

2023-10-16 16:08 UTC, shunki1006 commented
> 9/23の実験走行時にB3は機体を出していないのでこのフォルダは削除してもらえますか？ https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/tree/feature/waypoints_file/maps/tsukuba/20230923/b3
> 
> > @Alpaca-zip cartographerとslam_toolboxのウェイポイントナビゲーションではorange_ros2/orange_navigation/config/waypoints.yamlを使用していることは確認できたのですが, 今回の変更で移動させたkbkn_maps内のwaypointsをどこで使用しているのかが見つかりませんでした.
> > もし, 使用しているのであればご指摘お願いいたします.
> > また, kbkn_maps内のファイルを指定するように変更したい際にはorange_navigation内で出しているPRの方にもコメントいただけますと幸いです.
> 
> 以下です。 https://github.com/KBKN-Autonomous-Robotics-Lab/orange_ros2/blob/7aecec11b5da80e2ab86b0e8ca499bc506ad13dd/orange_navigation/src/waypoint_follower_client.cpp#L9
> 
> ただし、waypoint_follower_clientを含め、既存のorange_ros2/orange_navigationの内容は全面的に廃止(@koki0624 が作成してくれた[orange_navigaion](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation)に置き換え)をする予定なので、そちらの対応は[orange_navigaion](https://github.com/KBKN-Autonomous-Robotics-Lab/orange_navigation)の作業が落ち着いた後でよいと思います。

1点目のご指摘である, B3のフォルダを削除しました. 
2点目について承知しました. 置き換え作業が落ち着くまでは一旦放置します.

2023-10-16 16:10 UTC, shunki1006 commented
@Alpaca-zip またつくばの確認走行用のwaypointを一旦おいたファイルも入れたのでご確認いただけますと幸いです. 
細かい位置は現場に行かないとわからない部分もあると思うので当日設定しようと考えています.

2023-10-17 03:52 UTC, Alpaca-zip approved these changes
実際に走らせてみないと分かりませんが、以下の箇所は道の真ん中に寄りすぎな気がするので適宜実験走行で修正してください。

![tes](https://github.com/KBKN-Autonomous-Robotics-Lab/kbkn_maps/assets/84959376/77b884ea-2c47-493b-90c1-58fa3dc7b6ef)

2023-10-17 03:53 UTC, merged

2023-10-17 07:29 UTC, shunki1006 commented
> 実際に走らせてみないと分かりませんが、以下の箇所は道の真ん中に寄りすぎな気がするので適宜実験走行で修正してください。
> 
> ![tes](https://user-images.githubusercontent.com/84959376/275706105-77b884ea-2c47-493b-90c1-58fa3dc7b6ef.png)

ありがとうございます. 
当日, 確認走行用のブランチ切って対応します.